require("rvalle.plugins")
require("rvalle.remaps")
require("rvalle.options")
require("rvalle.themes")
require("rvalle.treesitter")
require("rvalle.telescope")
require("rvalle.cmp")
require("rvalle.lsp")
require("rvalle.null-ls")
require("rvalle.comment")
require("rvalle.colorizer")
require("rvalle.project")
require("rvalle.statusline")
require("rvalle.oil")
require("rvalle.illuminate")
require("rvalle.lspsaga")

-- testing without
-- require("rvalle.bufferline")
-- require("rvalle.dap")
