require("rvalle.plugins")
require("rvalle.remaps")
require("rvalle.options")
Utils = require("rvalle.utils")
vim.cmd([[command! -nargs=1 ChangeColorscheme lua Utils.change_colorscheme(<f-args>)]])

require("rvalle.themes")
require("rvalle.treesitter")
require("rvalle.telescope")
require("rvalle.nvimtree")
require("rvalle.lsp")
require("rvalle.cmp")
require("rvalle.null-ls")
require("rvalle.comment")
require("rvalle.colorizer")
require("rvalle.project")
require("rvalle.statusline")
require("rvalle.bufferline")
