local opt = vim.opt
local g = vim.g

opt.number = true
opt.relativenumber = true
opt.expandtab = false
opt.tabstop = 4
opt.shiftwidth = 4
opt.smartindent = true
opt.ignorecase = true
opt.smarttab = true
opt.clipboard = "unnamedplus"
opt.signcolumn = "yes"
opt.splitbelow = true
opt.splitright = true
opt.laststatus = 2
opt.showtabline = 2
opt.foldenable=false
opt.foldmethod="expr"
opt.foldexpr = "nvim_treesitter#foldexpr()"
opt.foldlevel = 99
opt.writebackup = false
opt.guifont = { "JetBrainsMono Nerd Font:h10" }
opt.updatetime = 100
opt.cursorline = true
opt.termguicolors = true
opt.background = "dark"
opt.showmode = false
opt.showcmd = false
opt.scrolloff = 10
opt.sidescrolloff = 10
opt.wrap = false
opt.swapfile = false

g.netrw_liststyle = 3
